version: '3.8'

services:
  tuvi-app:
    build:
      context: .
      dockerfile: apps/web/Dockerfile.dev
    container_name: tuvi-app
    ports:
      - "8950:3000"
    volumes:
      - .:/app
      - /app/apps/web/.next
      - /app/node_modules
      - /app/apps/web/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: unless-stopped
