/**
 * TEST CHUẨN TỬ VI - Nguyễn Đức Toàn
 * 28/01/1991 Dương Lịch, Giờ Ngọ (11-13h), Nam
 * Năm xem: 2026
 */

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const sandbox = {
    console: console, Math: Math, parseInt: parseInt, parseFloat: parseFloat,
    isNaN: isNaN, Date: Date, JSON: JSON, Array: Array, Object: Object,
    String: String, Number: Number, Error: Error, RegExp: RegExp, Map: Map, Set: Set
};
vm.createContext(sandbox);

['am-lich.js', 'tu-vi-calc.js', 'tu-vi-sao.js'].forEach(mod => {
    vm.runInContext(fs.readFileSync(path.join(__dirname, 'public', mod), 'utf8'), sandbox, { filename: mod });
});

const testCode = [
    '(function() {',
    '    var DIA_CHI = ["Tý", "Sửu", "Dần", "Mão", "Thìn", "Tỵ", "Ngọ", "Mùi", "Thân", "Dậu", "Tuất", "Hợi"];',
    '    var THIEN_CAN = ["Giáp", "Ất", "Bính", "Đinh", "Mậu", "Kỷ", "Canh", "Tân", "Nhâm", "Quý"];',
    '    var params = { ngay: 28, thang: 1, nam: 1991, gioSinh: 6, gioiTinh: "nam", namXem: 2026 };',
    '    var lasoData = TuViCalc.calculate(params);',
    '    TuViSao.anSao(lasoData);',
    '    var lines = [];',
    '    function log(s) { lines.push(s || ""); }',
    '',
    '    log("# KẾT QUẢ TEST CHUẨN TỬ VI");',
    '    log("");',
    '    log("> **Người test:** Nguyễn Đức Toàn");',
    '    log("> **Ngày chạy:** " + new Date().toISOString());',
    '    log("> **Source:** 100% output từ code tu-vi-calc.js + tu-vi-sao.js chạy trong Docker");',
    '    log("");',
    '    log("---");',
    '    log("");',
    '',
    '    // === 1. INPUT ===',
    '    log("## 1. THÔNG TIN ĐẦU VÀO");',
    '    log("");',
    '    log("| Trường | Giá trị |");',
    '    log("|---|---|");',
    '    log("| Họ tên | Nguyễn Đức Toàn |");',
    '    log("| Ngày sinh DL | 28/01/1991 |");',
    '    log("| Giờ sinh | Ngọ (11h-13h) - index 6 |");',
    '    log("| Giới tính | Nam |");',
    '    log("| Năm xem | 2026 |");',
    '    log("");',
    '',
    '    // === 2. ÂM LỊCH ===',
    '    log("## 2. CHUYỂN ĐỔI ÂM LỊCH");',
    '    log("");',
    '    log("| Trường | Giá trị |");',
    '    log("|---|---|");',
    '    log("| Ngày ÂL | " + lasoData.lunarDate.day + " |");',
    '    log("| Tháng ÂL | " + lasoData.lunarDate.month + " |");',
    '    log("| Năm ÂL | " + lasoData.lunarDate.year + " |");',
    '    log("| Nhuận | " + (lasoData.lunarDate.leap ? "Có" : "Không") + " |");',
    '    log("| Julian Day | " + lasoData.lunarDate.jd + " |");',
    '    log("| **Ngày ÂL đầy đủ** | **" + lasoData.lunarDate.day + "/" + lasoData.lunarDate.month + "/" + lasoData.lunarDate.year + "** |");',
    '    log("");',
    '',
    '    // === 3. CAN CHI ===',
    '    log("## 3. CAN CHI");',
    '    log("");',
    '    log("| Trường | Can | Chi | canIndex | chiIndex | Đầy đủ |");',
    '    log("|---|---|---|---|---|---|");',
    '    log("| Năm sinh | " + lasoData.canChiNam.can + " | " + lasoData.canChiNam.chi + " | " + lasoData.canChiNam.canIndex + " | " + lasoData.canChiNam.chiIndex + " | **" + lasoData.canChiNam.full + "** |");',
    '    log("| Tháng | " + lasoData.canChiThang.can + " | " + lasoData.canChiThang.chi + " | " + lasoData.canChiThang.canIndex + " | " + lasoData.canChiThang.chiIndex + " | " + lasoData.canChiThang.full + " |");',
    '    log("| Ngày | " + lasoData.canChiNgay.can + " | " + lasoData.canChiNgay.chi + " | " + lasoData.canChiNgay.canIndex + " | " + lasoData.canChiNgay.chiIndex + " | " + lasoData.canChiNgay.full + " |");',
    '    log("| Giờ | " + lasoData.canChiGio.can + " | " + lasoData.canChiGio.chi + " | " + lasoData.canChiGio.canIndex + " | " + lasoData.canChiGio.chiIndex + " | " + lasoData.canChiGio.full + " |");',
    '    log("| Năm xem | " + lasoData.canChiNamXem.can + " | " + lasoData.canChiNamXem.chi + " | " + lasoData.canChiNamXem.canIndex + " | " + lasoData.canChiNamXem.chiIndex + " | **" + lasoData.canChiNamXem.full + "** |");',
    '    log("");',
    '',
    '    // === 4. MỆNH CỤC ===',
    '    log("## 4. MỆNH & CỤC");',
    '    log("");',
    '    log("| Trường | Giá trị |");',
    '    log("|---|---|");',
    '    log("| Mệnh (Nạp Âm) | **" + lasoData.menhNapAm + "** |");',
    '    log("| Hành Mệnh | **" + lasoData.hanhMenh + "** |");',
    '    log("| Cục | **" + lasoData.cucName + "** (giá trị: " + lasoData.cucValue + ") |");',
    '    log("| Hành Cục | **" + lasoData.hanhCuc + "** |");',
    '    log("| Âm Dương | " + lasoData.amDuong + " |");',
    '    log("| Thuận/Nghịch | **" + (lasoData.thuan ? "THUẬN" : "NGHỊCH") + "** |");',
    '    log("");',
    '',
    '    // === 5. CUNG MỆNH THÂN ===',
    '    log("## 5. CUNG MỆNH & THÂN");',
    '    log("");',
    '    log("| Trường | Giá trị | Index |");',
    '    log("|---|---|---|");',
    '    log("| Cung Mệnh | **" + DIA_CHI[lasoData.cungMenhPos] + "** | " + lasoData.cungMenhPos + " |");',
    '    log("| Cung Thân | **" + DIA_CHI[lasoData.cungThanPos] + "** | " + lasoData.cungThanPos + " |");',
    '    log("| Thân Mệnh đồng cung | **" + (lasoData.thanMenhDongCung ? "CÓ" : "KHÔNG") + "** | - |");',
    '    log("| Chủ Mệnh | **" + TuViSao.getChuMenh(lasoData.cungMenhPos) + "** | - |");',
    '    log("| Chủ Thân | **" + TuViSao.getChuThan(lasoData.cungThanPos) + "** | - |");',
    '    log("");',
    '',
    '    // === 6. ĐẶC BIỆT ===',
    '    log("## 6. KIỂM TRA ĐẶC BIỆT");',
    '    log("");',
    '    log("| Trường | Giá trị |");',
    '    log("|---|---|");',
    '    log("| Âm Dương nghịch lý | " + (lasoData.amDuongNghichLy ? "CÓ" : "KHÔNG") + " |");',
    '    log("| Cục khắc Mệnh | " + (lasoData.cucKhacMenh ? "CÓ" : "KHÔNG") + " |");',
    '    log("| Tuần Không | " + DIA_CHI[lasoData.tuanTriet.tuan[0]] + " - " + DIA_CHI[lasoData.tuanTriet.tuan[1]] + " (index: " + lasoData.tuanTriet.tuan[0] + ", " + lasoData.tuanTriet.tuan[1] + ") |");',
    '    log("| Triệt Lộ | " + DIA_CHI[lasoData.tuanTriet.triet[0]] + " - " + DIA_CHI[lasoData.tuanTriet.triet[1]] + " (index: " + lasoData.tuanTriet.triet[0] + ", " + lasoData.tuanTriet.triet[1] + ") |");',
    '    log("");',
    '',
    '    // === 7. TỨ HÓA ===',
    '    log("## 7. TỨ HÓA");',
    '    log("");',
    '    log("### 7a. Tứ Hóa gốc (Can năm sinh: " + lasoData.canChiNam.can + " [" + lasoData.canChiNam.canIndex + "])");',
    '    log("");',
    '    var tuHoa = lasoData.tuHoa;',
    '    log("| Hóa | Sao được hóa | Vị trí cung | Cung |");',
    '    log("|---|---|---|---|");',
    '    ["Hoá Lộc", "Hoá Quyền", "Hoá Khoa", "Hoá Kỵ"].forEach(function(hoaName) {',
    '        var saoName = tuHoa[hoaName];',
    '        var foundCung = "?", foundCungName = "?";',
    '        for (var i = 0; i < 12; i++) {',
    '            var found = (lasoData.saoMap[i] || []).find(function(s) { return s.name === saoName; });',
    '            if (found) { foundCung = DIA_CHI[i]; foundCungName = lasoData.cungMap[i] || "?"; break; }',
    '        }',
    '        log("| " + hoaName + " | **" + saoName + "** | " + foundCung + " | " + foundCungName + " |");',
    '    });',
    '    log("");',
    '',
    '    log("### 7b. Lưu Tứ Hóa (Can năm xem: " + lasoData.canChiNamXem.can + " [" + lasoData.canChiNamXem.canIndex + "])");',
    '    log("");',
    '    var luuTuHoa = lasoData.luuTuHoa;',
    '    if (luuTuHoa) {',
    '        log("| Hóa | Sao được hóa | Vị trí cung | Cung |");',
    '        log("|---|---|---|---|");',
    '        ["Hoá Lộc", "Hoá Quyền", "Hoá Khoa", "Hoá Kỵ"].forEach(function(hoaName) {',
    '            var saoName = luuTuHoa[hoaName];',
    '            var foundCung = "?", foundCungName = "?";',
    '            for (var i = 0; i < 12; i++) {',
    '                var found = (lasoData.saoMap[i] || []).find(function(s) { return s.name === saoName; });',
    '                if (found) { foundCung = DIA_CHI[i]; foundCungName = lasoData.cungMap[i] || "?"; break; }',
    '            }',
    '            log("| Lưu " + hoaName + " | **" + saoName + "** | " + foundCung + " | " + foundCungName + " |");',
    '        });',
    '    }',
    '    log("");',
    '',
    '    // === 8. TRÀNG SINH ===',
    '    log("## 8. TRÀNG SINH");',
    '    log("");',
    '    log("| Cung | Trạng thái |");',
    '    log("|---|---|");',
    '    for (var i = 0; i < 12; i++) {',
    '        log("| " + DIA_CHI[i] + " | " + (lasoData.truongSinhMap[i] || "-") + " |");',
    '    }',
    '    log("");',
    '',
    '    // === 9. 12 CUNG CHI TIẾT ===',
    '    log("## 9. CHI TIẾT 12 CUNG + SAO");',
    '    log("");',
    '    for (var i = 0; i < 12; i++) {',
    '        var cungName = lasoData.cungMap[i] || "?";',
    '        var truongSinh = lasoData.truongSinhMap[i] || "";',
    '        var saoList = lasoData.saoMap[i] || [];',
    '        var marker = "";',
    '        if (lasoData.cungMenhPos === i) marker += " ★MỆNH";',
    '        if (lasoData.cungThanPos === i) marker += " ★THÂN";',
    '        if (lasoData.tuanTriet.tuan.indexOf(i) >= 0) marker += " [TUẦN]";',
    '        if (lasoData.tuanTriet.triet.indexOf(i) >= 0) marker += " [TRIỆT]";',
    '        log("### Cung " + DIA_CHI[i] + " — " + cungName + marker);',
    '        log("");',
    '        log("- **Tràng Sinh:** " + truongSinh);',
    '        var chinhTinh = saoList.filter(function(s) { return s.type === "chinh"; });',
    '        var phuTinh = saoList.filter(function(s) { return s.type === "phu"; });',
    '        var luuTinh = saoList.filter(function(s) { return s.type === "luu"; });',
    '        if (chinhTinh.length > 0) {',
    '            log("- **Chính tinh:** " + chinhTinh.map(function(s) {',
    '                var extra = "";',
    '                if (s.hoa) extra += " [Hóa " + s.hoa + "]";',
    '                if (s.luuHoa) extra += " {Lưu Hóa " + s.luuHoa + "}";',
    '                return s.name + extra;',
    '            }).join(", "));',
    '        } else {',
    '            log("- **Chính tinh:** _(trống)_");',
    '        }',
    '        if (phuTinh.length > 0) {',
    '            log("- **Phụ tinh:** " + phuTinh.map(function(s) {',
    '                var mark = "";',
    '                if (s.nature === "cat") mark = "(+)";',
    '                else if (s.nature === "hung") mark = "(-)";',
    '                var extra = "";',
    '                if (s.hoa) extra += " [Hóa " + s.hoa + "]";',
    '                if (s.luuHoa) extra += " {Lưu Hóa " + s.luuHoa + "}";',
    '                return s.name + mark + extra;',
    '            }).join(", "));',
    '        }',
    '        if (luuTinh.length > 0) {',
    '            log("- **Sao lưu niên:** " + luuTinh.map(function(s) {',
    '                var mark = "";',
    '                if (s.nature === "cat") mark = "(+)";',
    '                else if (s.nature === "hung") mark = "(-)";',
    '                return s.name + mark;',
    '            }).join(", "));',
    '        }',
    '        log("");',
    '    }',
    '',
    '    // === 10. ĐẠI VẬN ===',
    '    log("## 10. ĐẠI VẬN");',
    '    log("");',
    '    log("| # | Cung | Tên cung | Tuổi | Năm | Hiện tại |");',
    '    log("|---|---|---|---|---|---|");',
    '    lasoData.daiVan.forEach(function(dv, idx) {',
    '        var isCurrent = 2026 >= dv.namFrom && 2026 <= dv.namTo;',
    '        var cn = lasoData.cungMap[dv.cungPos] || "?";',
    '        log("| " + (idx+1) + " | " + DIA_CHI[dv.cungPos] + " | " + cn + " | " + dv.tuoiFrom + "-" + dv.tuoiTo + " | " + dv.namFrom + "-" + dv.namTo + " | " + (isCurrent ? "◀ **HIỆN TẠI**" : "") + " |");',
    '    });',
    '    log("");',
    '    if (lasoData.daiVanHienTai) {',
    '        var dv = lasoData.daiVanHienTai;',
    '        log("**Đại Vận hiện tại:** Cung **" + DIA_CHI[dv.cungPos] + "** (" + (lasoData.cungMap[dv.cungPos] || "") + "), tuổi " + dv.tuoiFrom + "-" + dv.tuoiTo + ", năm " + dv.namFrom + "-" + dv.namTo);',
    '        var dvSao = lasoData.saoMap[dv.cungPos] || [];',
    '        log("");',
    '        log("Sao trong cung ĐV: " + dvSao.map(function(s) { return s.name; }).join(", "));',
    '    }',
    '    log("");',
    '',
    '    // === 11. TIỂU VẬN ===',
    '    log("## 11. TIỂU VẬN NĂM 2026");',
    '    log("");',
    '    log("| Trường | Giá trị |");',
    '    log("|---|---|");',
    '    log("| Tuổi mụ | " + lasoData.tuoi + " |");',
    '    log("| Cung Tiểu Vận | **" + DIA_CHI[lasoData.tieuVan.cungPos] + "** (" + (lasoData.cungMap[lasoData.tieuVan.cungPos] || "") + ") |");',
    '    var tvSao = lasoData.saoMap[lasoData.tieuVan.cungPos] || [];',
    '    log("| Sao trong cung TV | " + tvSao.map(function(s) { return s.name; }).join(", ") + " |");',
    '    log("");',
    '',
    '    // === 12. VỊ TRÍ 14 CHÍNH TINH ===',
    '    log("## 12. VỊ TRÍ 14 CHÍNH TINH");',
    '    log("");',
    '    log("| Sao | Cung (Địa Chi) | Cung (Tên) | Index |");',
    '    log("|---|---|---|---|");',
    '    var chinhTinhNames = ["Tử Vi", "Thiên Cơ", "Thái Dương", "Vũ Khúc", "Thiên Đồng", "Liêm Trinh", "Thiên Phủ", "Thái Âm", "Tham Lang", "Cự Môn", "Thiên Tướng", "Thiên Lương", "Thất Sát", "Phá Quân"];',
    '    chinhTinhNames.forEach(function(saoName) {',
    '        for (var i = 0; i < 12; i++) {',
    '            var found = (lasoData.saoMap[i] || []).find(function(s) { return s.name === saoName; });',
    '            if (found) {',
    '                log("| " + saoName + " | " + DIA_CHI[i] + " | " + (lasoData.cungMap[i] || "?") + " | " + i + " |");',
    '                break;',
    '            }',
    '        }',
    '    });',
    '    log("");',
    '',
    '    // === 13. PHỤ TINH QUAN TRỌNG ===',
    '    log("## 13. VỊ TRÍ PHỤ TINH QUAN TRỌNG");',
    '    log("");',
    '    log("| Sao | Cung (Địa Chi) | Cung (Tên) | Tính chất |");',
    '    log("|---|---|---|---|");',
    '    var phuTinhNames = ["Tả Phụ", "Hữu Bật", "Văn Xương", "Văn Khúc", "Thiên Khôi", "Thiên Việt", "Lộc Tồn", "Kình Dương", "Đà La", "Thiên Mã", "Hoả Tinh", "Linh Tinh", "Địa Không", "Địa Kiếp", "Đào Hoa", "Hồng Loan", "Thiên Hỷ", "Thiên Hình"];',
    '    phuTinhNames.forEach(function(saoName) {',
    '        for (var i = 0; i < 12; i++) {',
    '            var found = (lasoData.saoMap[i] || []).find(function(s) { return s.name === saoName; });',
    '            if (found) {',
    '                var nature = found.nature === "cat" ? "Cát (+)" : found.nature === "hung" ? "Hung (-)" : "Trung tính";',
    '                log("| " + saoName + " | " + DIA_CHI[i] + " | " + (lasoData.cungMap[i] || "?") + " | " + nature + " |");',
    '                break;',
    '            }',
    '        }',
    '    });',
    '    log("");',
    '',
    '    // === 14. RAW TỨ HÓA ===',
    '    log("## 14. RAW DATA TỨ HÓA");',
    '    log("");',
    '    log("### tuHoa (gốc - Can " + lasoData.canChiNam.can + ")");',
    '    log(JSON.stringify(lasoData.tuHoa, null, 2));',
    '    log("");',
    '    log("### luuTuHoa (lưu niên - Can " + lasoData.canChiNamXem.can + ")");',
    '    log(JSON.stringify(lasoData.luuTuHoa, null, 2));',
    '    log("");',
    '    log("### nhomTuVi (position index)");',
    '    log(JSON.stringify(lasoData.nhomTuVi, null, 2));',
    '    log("");',
    '    log("### nhomThienPhu (position index)");',
    '    log(JSON.stringify(lasoData.nhomThienPhu, null, 2));',
    '    log("");',
    '',
    '    // === 15. VERIFY HOÁ ===',
    '    log("## 15. VERIFY - SAO CÓ GẮN HOÁ");',
    '    log("");',
    '    log("| Cung | Tên cung | Sao | Hóa gốc | Lưu Hóa |");',
    '    log("|---|---|---|---|---|");',
    '    for (var i = 0; i < 12; i++) {',
    '        var saoList = lasoData.saoMap[i] || [];',
    '        saoList.forEach(function(s) {',
    '            if (s.hoa || s.luuHoa) {',
    '                log("| " + DIA_CHI[i] + " | " + (lasoData.cungMap[i] || "") + " | " + s.name + " | " + (s.hoa || "-") + " | " + (s.luuHoa || "-") + " |");',
    '            }',
    '        });',
    '    }',
    '    log("");',
    '    log("---");',
    '    log("");',
    '    log("_Test hoàn thành. Output 100% từ code chạy trong Docker container._");',
    '',
    '    return lines.join("\\n");',
    '})();'
].join('\n');

const result = vm.runInContext(testCode, sandbox, { filename: 'test' });

const output = result.replace(/\\n/g, '\n');
fs.writeFileSync(path.join(__dirname, 'data', 'TEST_CHUAN_NGUYEN_DUC_TOAN.md'), output, 'utf8');
console.log('✅ Đã lưu kết quả vào: data/TEST_CHUAN_NGUYEN_DUC_TOAN.md');
console.log('');
console.log(output);
